/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/runs': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Runs */
    get: operations['list_runs_api_runs_get']
    put?: never
    /** Create Run */
    post: operations['create_run_api_runs_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/runs/{run_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Run */
    get: operations['get_run_api_runs__run_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/runs/{run_id}/lines': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Run Lines */
    get: operations['get_run_lines_api_runs__run_id__lines_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/runs/{run_id}/video': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Run Video */
    get: operations['get_run_video_api_runs__run_id__video_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/runs/{run_id}/review': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Review Run */
    post: operations['review_run_api_runs__run_id__review_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/runs/{run_id}/continue': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Continue Run */
    post: operations['continue_run_api_runs__run_id__continue_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Health */
    get: operations['health_api_health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** AlignedWordSchema */
    AlignedWordSchema: {
      op: components['schemas']['DiffOp'] | null
      /** Expected */
      expected: string | null
      /** Heard */
      heard: string | null
    }
    /** CreateRunRequest */
    CreateRunRequest: {
      /** Idea */
      idea: string
    }
    /**
     * DiffOp
     * @enum {string}
     */
    DiffOp: 'sub' | 'del' | 'ins'
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /** HealthResponse */
    HealthResponse: {
      /** Status */
      status: string
    }
    /** LineReportSchema */
    LineReportSchema: {
      /** Shot Id */
      shot_id: string
      /** Speaker */
      speaker: string
      /** Speaker Name */
      speaker_name: string
      /** Text */
      text: string
      /** Locked */
      locked: boolean
      /** Attempt */
      attempt: number | null
      /** Heard */
      heard: string | null
      /** Wer */
      wer: number | null
      /** Diff */
      diff: components['schemas']['WordDiffSchema'][]
      /** Alignment */
      alignment: components['schemas']['AlignedWordSchema'][]
      /** Speaker Matches */
      speaker_matches: boolean | null
    }
    /** ReviewDecisionRequest */
    ReviewDecisionRequest: {
      /** Approve */
      approve: boolean
    }
    /** RunLinesResponse */
    RunLinesResponse: {
      /** Items */
      items: components['schemas']['LineReportSchema'][]
    }
    /** RunListResponse */
    RunListResponse: {
      /** Items */
      items: components['schemas']['RunSummarySchema'][]
    }
    /** RunSchema */
    RunSchema: {
      /** Id */
      id: string
      /** Idea */
      idea: string
      status: components['schemas']['RunStatus']
      /** Cost Usd */
      cost_usd: number
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Video Url */
      video_url?: string | null
      current_step: components['schemas']['StepName'] | null
      /** Review Reason */
      review_reason: string | null
      /** Error */
      error: string | null
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string
      /** Finished At */
      finished_at: string | null
      /** Steps */
      steps: components['schemas']['RunStepSchema'][]
      /**
       * Can Continue
       * @default false
       */
      can_continue: boolean
    }
    /**
     * RunStatus
     * @enum {string}
     */
    RunStatus: 'queued' | 'running' | 'done' | 'needs_review' | 'failed'
    /** RunStepSchema */
    RunStepSchema: {
      /** Id */
      id: string
      name: components['schemas']['StepName']
      status: components['schemas']['StepStatus']
      /** Attempt */
      attempt: number
      /** Detail */
      detail: string | null
      /** Cost Usd */
      cost_usd: number
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Finished At */
      finished_at: string | null
    }
    /** RunSummarySchema */
    RunSummarySchema: {
      /** Id */
      id: string
      /** Idea */
      idea: string
      status: components['schemas']['RunStatus']
      /** Cost Usd */
      cost_usd: number
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Video Url */
      video_url?: string | null
    }
    /**
     * StepName
     * @enum {string}
     */
    StepName:
      | 'brief'
      | 'script'
      | 'script_check'
      | 'cast'
      | 'portraits'
      | 'portrait_check'
      | 'scene'
      | 'render'
      | 'scene_check'
      | 'shot_fix'
      | 'final'
    /**
     * StepStatus
     * @enum {string}
     */
    StepStatus: 'running' | 'ok' | 'rejected' | 'failed'
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
      /** Input */
      input?: unknown
      /** Context */
      ctx?: Record<string, never>
    }
    /** WordDiffSchema */
    WordDiffSchema: {
      op: components['schemas']['DiffOp']
      /** Expected */
      expected: string | null
      /** Heard */
      heard: string | null
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  list_runs_api_runs_get: {
    parameters: {
      query?: {
        limit?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RunListResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_run_api_runs_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateRunRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RunSchema']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_run_api_runs__run_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        run_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RunSchema']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_run_lines_api_runs__run_id__lines_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        run_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RunLinesResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_run_video_api_runs__run_id__video_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        run_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  review_run_api_runs__run_id__review_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        run_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ReviewDecisionRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RunSchema']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  continue_run_api_runs__run_id__continue_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        run_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RunSchema']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  health_api_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthResponse']
        }
      }
    }
  }
}
