BRIEF_FILE = 'brief.json'
SCRIPT_FILE = 'script.json'
CAST_FILE = 'cast.json'
SCENE_FILE = 'scene.json'
SHOT_FIX_FILE = 'shot_fix.json'
MANIFEST_FILE = 'manifest.json'
FINAL_VIDEO_FILE = 'final.mp4'

REFS_DIR = 'refs'
TAKES_DIR = 'takes'
REQUESTS_DIR = 'requests'

CRITIQUE_FILE_TEMPLATE = 'critique-{revision}.json'
PORTRAIT_FILE_TEMPLATE = 'refs/{character_id}-{round}.jpg'
PORTRAITS_CHECK_FILE_TEMPLATE = 'portraits-{round}.json'
ATTEMPT_FILE_TEMPLATE = 'attempt-{attempt}.json'
TAKE_FILE_TEMPLATE = 'takes/{attempt}.mp4'
REQUEST_FILE_TEMPLATE = 'requests/{attempt}.json'
SCENE_CHECK_FILE_TEMPLATE = 'judge-{attempt}.json'
TAKE_AUDIO_FILE_TEMPLATE = 'checks/audio-{attempt}.mp3'
WINDOW_DIR_TEMPLATE = 'checks/window-{attempt}-{shot_id}'
WINDOW_AUDIO_FILE = 'audio.mp3'
