FFMPEG_BINARY = 'ffmpeg'
FFPROBE_BINARY = 'ffprobe'

VIDEO_ASPECT_RATIO = '9:16'
VIDEO_ASPECT_TOLERANCE = 0.02
PORTRAIT_ASPECT_RATIO = '9:16'
JPEG_MIME_TYPE = 'image/jpeg'
PORTRAIT_FILE_EXTENSION = '.jpg'

JUDGE_FRAMES_PER_SECOND = 6
JUDGE_WINDOW_PADDING_SECONDS = 0.5
JUDGE_FRAME_WIDTH = 480
MAX_JUDGE_FRAMES_PER_WINDOW = 24
MAX_SEED = 2_147_483_647
