OPENROUTER_BASE_URL = 'https://openrouter.ai/api/v1'
CHAT_COMPLETIONS_PATH = '/chat/completions'
IMAGES_PATH = '/images'
VIDEOS_PATH = '/videos'
TRANSCRIPTIONS_PATH = '/audio/transcriptions'

HTTP_TIMEOUT_SECONDS = 120.0
RETRYABLE_STATUS_CODES = frozenset({408, 429, 500, 502, 503, 504})
MAX_HTTP_RETRIES = 4
BACKOFF_BASE_SECONDS = 2.0
BACKOFF_MAX_SECONDS = 30.0

VIDEO_POLL_INTERVAL_SECONDS = 10.0
VIDEO_POLL_TIMEOUT_SECONDS = 15 * 60.0
VIDEO_JOB_PATH_TEMPLATE = '/videos/{job_id}'
VIDEO_CONTENT_PATH_TEMPLATE = '/videos/{job_id}/content'

JSON_SCHEMA_RESPONSE_TYPE = 'json_schema'
IMAGE_OUTPUT_FORMAT = 'jpeg'
SPEECH_RESPONSE_FORMAT = 'verbose_json'
SPEECH_TIMESTAMP_GRANULARITIES = ('word', 'segment')
SPEECH_LANGUAGE = 'en'
SPEECH_AUDIO_FORMAT = 'mp3'
MISSING_API_KEY_MESSAGE = 'OPENROUTER_API_KEY is not set: add it to .env and restart'
