MIN_SCENE_SECONDS = 8
MAX_SCENE_SECONDS = 30
MIN_SHOT_SECONDS = 2
MAX_SHOT_SECONDS = 15
MAX_SHOTS = 4
MAX_CHARACTERS = 3

MAX_OWN_LINE_WORDS = 12
MAX_WORDS_PER_SECOND = 2.5

MAX_SCRIPT_REVISIONS = 20
MAX_PORTRAIT_REDRAWS = 5
MAX_SCENE_ATTEMPTS = 3
MAX_SCHEMA_RETRIES = 2

FIRST_ATTEMPT = 1
REBUILD_ATTEMPT = 3

ADULT_AGE = 18
CHARACTER_ID_PATTERN = r'^c[1-3]$'
SHOT_ID_PATTERN = r'^s[1-4]$'
