CRITIC_MIN_SCORE = 1
CRITIC_MAX_SCORE = 10
CRITIC_PASS_SCORE = 7

PORTRAIT_MIN_SCORE = 0
PORTRAIT_MAX_SCORE = 5
PORTRAIT_REJECT_BELOW = 3

JUDGE_MIN_SCORE = 0
JUDGE_MAX_SCORE = 10
JUDGE_PASS_SCORE = 5
PRESENCE_PASS_SCORE = 10
